### ISSUE TITLE
kernel size of branch3 should be 5. not 3

### ISSUE THREAD

**Issue by modyuan** [Lornatang/GoogLeNet-PyTorch#1]

**Comment by Lornatang** [comment]
Fixed. Thank you

**Comment by mykytahordia** [comment]
this issue is still present and can mislead someone🥲

**Comment by mykytahordia** [comment]
Oh, I see why it is an issue 
https://github.com/pytorch/vision/issues/906

Because someone once have made a mistake, and everyone now has no choice but to use slightly invalid model😅

**Comment by Lornatang** [comment]
Yes, @modyuan @NikitaGordia are right. Retraining based on the fine-tuned model is too resource-intensive, but the results are also pretty close
